### ISSUE TITLE
When i start the container i get  "Cannot import name 'appengine' from 'requests.packages.urllib3.contrib'

### ISSUE THREAD

**Issue by AlexJoom** [aiondemand/AIOD-rest-api#44]
I m using the develop branch and i follow the readme guide.
I have initiated succesfully the mysql docker container but i get an error in the initialization of the ai4eu_server_demo container

``` docker run --network sql-network -it -p 8000:8000 --name apiserver ai4eu_server_demo```
```
/app/database/model/presentation.py:9: SAWarning: Reassigning polymorphic association for identity 'publication' from <Mapper at 0x7f601b5b4590; OrmPublication> to <Mapper at 0x7f601b50a810; OrmPresentation>: Check for duplicate use of 'publication' as value for polymorphic_identity.
  class OrmPresentation(OrmAIResource):
Traceback (most recent call last):
  File "/home/apprunner/.local/lib/python3.11/site-packages/requests_toolbelt/_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/home/apprunner/.local/lib/python3.11/site-packages/urllib3/contrib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 21, in <module>
    from authentication import get_current_user
  File "/app/authentication.py", line 6, in <module>
    from keycloak import KeycloakOpenID, KeycloakError
  File "/home/apprunner/.local/lib/python3.11/site-packages/keycloak/__init__.py", line 43, in <module>
    from .keycloak_admin import KeycloakAdmin
  File "/home/apprunner/.local/lib/python3.11/site-packages/keycloak/keycloak_admin.py", line 35, in <module>
    from requests_toolbelt import MultipartEncoder
  File "/home/apprunner/.local/lib/python3.11/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/home/apprunner/.local/lib/python3.11/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/home/apprunner/.local/lib/python3.11/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/home/apprunner/.local/lib/python3.11/site-packages/requests_toolbelt/_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/home/apprunner/.local/lib/python3.11/site-packages/urllib3/contrib/__init__.py)

```

**Comment by AlexJoom** [comment]
I m closing this, i ll try the tagged versions instead of the Develop branch, my bad!
