### ISSUE TITLE
When i start the container i get "Cannot import name 'appengine' from 'requests.packages.urllib3.contrib'

### ISSUE THREAD

**Issue by AlexJoom** [aiondemand/AIOD-rest-api#45]
Steps to reproduce

1.  `git checkout tags/0.3.20220501 -b 0.3.20220501`
2.  Create the docker network & Initiaze the mysql container (this works fine)
3. `docker build --tag ai4eu_server_demo:latest -f Dockerfile .` 
4.  When i run command

`docker run --network sql-network -it -p 8000:8000 --name apiserver ai4eu_server_demo`

I get the following errror (and the container fails)

```
/app/database/model/presentation.py:9: SAWarning: Reassigning polymorphic association for identity 'publication' from <Mapper at 0x7fc4cb4a0750; OrmPublication> to <Mapper at 0x7fc4cb3f6910; OrmPresentation>: Check for duplicate use of 'publication' as value for polymorphic_identity.
  class OrmPresentation(OrmAIResource):
Traceback (most recent call last):
  File "/home/apprunner/.local/lib/python3.11/site-packages/requests_toolbelt/_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/home/apprunner/.local/lib/python3.11/site-packages/urllib3/contrib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 21, in <module>
    from authentication import get_current_user
  File "/app/authentication.py", line 6, in <module>
    from keycloak import KeycloakOpenID, KeycloakError
  File "/home/apprunner/.local/lib/python3.11/site-packages/keycloak/__init__.py", line 43, in <module>
    from .keycloak_admin import KeycloakAdmin
  File "/home/apprunner/.local/lib/python3.11/site-packages/keycloak/keycloak_admin.py", line 35, in <module>
    from requests_toolbelt import MultipartEncoder
  File "/home/apprunner/.local/lib/python3.11/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/home/apprunner/.local/lib/python3.11/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/home/apprunner/.local/lib/python3.11/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/home/apprunner/.local/lib/python3.11/site-packages/requests_toolbelt/_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/home/apprunner/.local/lib/python3.11/site-packages/urllib3/contrib/__init__.py)

```

I also tried the same with the Develop branch

**Comment by josvandervelde** [comment]
Thanks for the bug report, Alexandros.
We haven't monitored the issues closely, so noone responded to this issue. I'm pretty sure it was fixed soon though. I'm closing the issue now, feel free to re-open it if anything is still wrong.
