### ISSUE TITLE
Error while populating database: HuggingFaceDatasetConnector - HuggingFace API breaking change and duplicate platform_id's

### ISSUE THREAD

**Issue by mtkinit** [aiondemand/AIOD-rest-api#62]
Hi,

When we try to populate datasets in a local instance of AIoD REST API (we followed the README), it crashed when we wanted to fetch HuggingFace datasets.

We investigated the issue and we found solution for one of two issues (therefore, we're only creating an issue and not a PR).

## Issue 1 - HuggingFace API breaking change
3 weeks ago, HuggingFace changed the behavior of one of the functions in the `datasets` library - `list_datasets`. Now, it sometimes returns a `list` and sometimes an `Iterable`, depending on the parameters. Before that, it always returned a `list`. In our code, we try to use slicing on what this function returns, which doesn't work on `Iterable`. We therefore propose following change in the [`HuggingFaceDatasetConnector`](https://github.com/aiondemand/AIOD-rest-api/blob/develop/src/connectors/huggingface/huggingface_dataset_connector.py):
```python
# Replace this
for dataset in datasets.list_datasets(with_details=True)[:limit]:

# with this
import itertools
...
for dataset in itertools.islice(datasets.list_datasets(with_details=True), limit):
```

References:
* [HuggingFace datasets.list_datasets (see sources and return type - sometimes list, sometimes Iterable through HfApi.list_datasets)](https://huggingface.co/docs/datasets/v2.12.0/en/package_reference/loading_methods#datasets.list_datasets)
* [HuggingFace HfApi.list_datasets (see sources and return type)](https://huggingface.co/docs/huggingface_hub/v0.15.1/en/package_reference/hf_api#huggingface_hub.HfApi.list_datasets)

## Issue 2 - sqlalchemy.exc.IntegrityError: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'task_categories:token-classification' for key 'keyword.name'")
After we fixed previous error, we tried to populate database with 5 HuggingFace datasets. We got following error caused by a duplicate combination of fields:
```sh
2023-06-05 14:21:50,224 INFO sqlalchemy.engine.Engine [no key 0.00013s] ()
2023-06-05 14:21:50,249 INFO sqlalchemy.engine.Engine COMMIT
2023-06-05 14:21:50,250 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-06-05 14:21:50,280 INFO sqlalchemy.engine.Engine SELECT publication.platform, publication.platform_identifier, publication.title, publication.doi, publication.creators, publication.access_right, publication.date_created, publication.date_published, publication.url, publication.identifier, publication.license_identifier, publication.resource_type_identifier 
FROM publication
2023-06-05 14:21:50,280 INFO sqlalchemy.engine.Engine [generated in 0.00019s] ()
2023-06-05 14:21:50,284 INFO sqlalchemy.engine.Engine SELECT dataset.platform, dataset.platform_identifier, dataset.description, dataset.name, dataset.same_as, dataset.contact, dataset.creator, dataset.publisher, dataset.date_modified, dataset.date_published, dataset.funder, dataset.is_accessible_for_free, dataset.issn, dataset.size, dataset.spatial_coverage, dataset.temporal_coverage_from, dataset.temporal_coverage_to, dataset.version, dataset.identifier, dataset.license_identifier 
FROM dataset
2023-06-05 14:21:50,284 INFO sqlalchemy.engine.Engine [generated in 0.00015s] ()
2023-06-05 14:21:59,398 INFO sqlalchemy.engine.Engine SELECT publication.platform, publication.platform_identifier, publication.title, publication.doi, publication.creators, publication.access_right, publication.date_created, publication.date_published, publication.url, publication.identifier, publication.license_identifier, publication.resource_type_identifier 
FROM publication 
WHERE publication.platform = %s AND publication.platform_identifier = %s
2023-06-05 14:21:59,398 INFO sqlalchemy.engine.Engine [generated in 0.00020s] ('huggingface', 'veyseh-et-al-2020-what')
2023-06-05 14:21:59,399 INFO sqlalchemy.engine.Engine INSERT INTO ai_asset (type) VALUES (%s)
2023-06-05 14:21:59,399 INFO sqlalchemy.engine.Engine [generated in 0.00012s] ('publication',)
2023-06-05 14:21:59,402 INFO sqlalchemy.engine.Engine INSERT INTO publication (platform, platform_identifier, title, doi, creators, access_right, date_created, date_published, url, identifier, license_identifier, resource_type_identifier) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
2023-06-05 14:21:59,402 INFO sqlalchemy.engine.Engine [generated in 0.00019s] ('huggingface', 'veyseh-et-al-2020-what', '{What Does This Acronym Mean? Introducing a New Dataset for Acronym Identification and Disambiguation}', None, None, None, None, None, 'https://arxiv.org/pdf/2010.14678v1.pdf', 1, None, None)
2023-06-05 14:21:59,404 INFO sqlalchemy.engine.Engine SELECT dataset.platform, dataset.platform_identifier, dataset.description, dataset.name, dataset.same_as, dataset.contact, dataset.creator, dataset.publisher, dataset.date_modified, dataset.date_published, dataset.funder, dataset.is_accessible_for_free, dataset.issn, dataset.size, dataset.spatial_coverage, dataset.temporal_coverage_from, dataset.temporal_coverage_to, dataset.version, dataset.identifier, dataset.license_identifier 
FROM dataset 
WHERE dataset.platform = %s AND dataset.platform_identifier = %s
2023-06-05 14:21:59,404 INFO sqlalchemy.engine.Engine [generated in 0.00015s] ('huggingface', 'acronym_identification')
2023-06-05 14:21:59,405 INFO sqlalchemy.engine.Engine INSERT INTO ai_asset (type) VALUES (%s)
2023-06-05 14:21:59,405 INFO sqlalchemy.engine.Engine [cached since 0.005521s ago] ('dataset',)
2023-06-05 14:21:59,407 INFO sqlalchemy.engine.Engine INSERT INTO license (name) VALUES (%s)
2023-06-05 14:21:59,407 INFO sqlalchemy.engine.Engine [generated in 0.00015s] ('mit',)
2023-06-05 14:21:59,410 INFO sqlalchemy.engine.Engine INSERT INTO keyword (name) VALUES (%s)
2023-06-05 14:21:59,410 INFO sqlalchemy.engine.Engine [generated in 0.00015s] ('task_categories:token-classification',)
2023-06-05 14:21:59,411 INFO sqlalchemy.engine.Engine INSERT INTO keyword (name) VALUES (%s)
2023-06-05 14:21:59,411 INFO sqlalchemy.engine.Engine [cached since 0.001265s ago] ('annotations_creators:expert-generated',)
2023-06-05 14:21:59,411 INFO sqlalchemy.engine.Engine INSERT INTO keyword (name) VALUES (%s)
2023-06-05 14:21:59,412 INFO sqlalchemy.engine.Engine [cached since 0.00168s ago] ('language_creators:found',)
2023-06-05 14:21:59,412 INFO sqlalchemy.engine.Engine INSERT INTO keyword (name) VALUES (%s)
2023-06-05 14:21:59,412 INFO sqlalchemy.engine.Engine [cached since 0.002021s ago] ('multilinguality:monolingual',)
2023-06-05 14:21:59,412 INFO sqlalchemy.engine.Engine INSERT INTO keyword (name) VALUES (%s)
2023-06-05 14:21:59,412 INFO sqlalchemy.engine.Engine [cached since 0.00242s ago] ('size_categories:10K<n<100K',)
2023-06-05 14:21:59,413 INFO sqlalchemy.engine.Engine INSERT INTO keyword (name) VALUES (%s)
2023-06-05 14:21:59,413 INFO sqlalchemy.engine.Engine [cached since 0.00285s ago] ('source_datasets:original',)
2023-06-05 14:21:59,413 INFO sqlalchemy.engine.Engine INSERT INTO keyword (name) VALUES (%s)
2023-06-05 14:21:59,413 INFO sqlalchemy.engine.Engine [cached since 0.003237s ago] ('language:en',)
2023-06-05 14:21:59,413 INFO sqlalchemy.engine.Engine INSERT INTO keyword (name) VALUES (%s)
2023-06-05 14:21:59,414 INFO sqlalchemy.engine.Engine [cached since 0.003655s ago] ('license:mit',)
2023-06-05 14:21:59,414 INFO sqlalchemy.engine.Engine INSERT INTO keyword (name) VALUES (%s)
2023-06-05 14:21:59,414 INFO sqlalchemy.engine.Engine [cached since 0.004077s ago] ('acronym-identification',)
2023-06-05 14:21:59,414 INFO sqlalchemy.engine.Engine INSERT INTO keyword (name) VALUES (%s)
2023-06-05 14:21:59,414 INFO sqlalchemy.engine.Engine [cached since 0.004426s ago] ('arxiv:2010.14678',)
2023-06-05 14:21:59,415 INFO sqlalchemy.engine.Engine INSERT INTO dataset (platform, platform_identifier, description, name, same_as, contact, creator, publisher, date_modified, date_published, funder, is_accessible_for_free, issn, size, spatial_coverage, temporal_coverage_from, temporal_coverage_to, version, identifier, license_identifier) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
2023-06-05 14:21:59,415 INFO sqlalchemy.engine.Engine [generated in 0.00020s] ('huggingface', 'acronym_identification', 'Acronym identification training and development sets for the acronym identification task at SDU@AAAI-21.', 'acronym_identification', 'https://huggingface.co/datasets/acronym_identification', None, None, None, datetime.datetime(2023, 1, 25, 14, 18, 28, tzinfo=tzlocal()), None, None, 1, None, None, None, None, None, None, 2, 1)
2023-06-05 14:21:59,416 INFO sqlalchemy.engine.Engine INSERT INTO dataset_publication_link (dataset_identifier, publication_identifier) VALUES (%s, %s)
2023-06-05 14:21:59,416 INFO sqlalchemy.engine.Engine [generated in 0.00011s] (2, 1)
2023-06-05 14:21:59,418 INFO sqlalchemy.engine.Engine INSERT INTO dataset_keyword_link (dataset_identifier, keyword_identifier) VALUES (%s, %s)
2023-06-05 14:21:59,418 INFO sqlalchemy.engine.Engine [generated in 0.00016s] ((2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10))
2023-06-05 14:21:59,420 INFO sqlalchemy.engine.Engine INSERT INTO data_download (content_url, content_size_kb, description, encoding_format, name, dataset_identifier) VALUES (%s, %s, %s, %s, %s, %s)
2023-06-05 14:21:59,420 INFO sqlalchemy.engine.Engine [generated in 0.00016s] ('https://huggingface.co/datasets/acronym_identification/resolve/refs%2Fconvert%2Fparquet/default/acronym_identification-test.parquet', 206100, 'acronym_identification. Config: default. Split: test', None, 'acronym_identification-test.parquet', 2)
2023-06-05 14:21:59,421 INFO sqlalchemy.engine.Engine INSERT INTO data_download (content_url, content_size_kb, description, encoding_format, name, dataset_identifier) VALUES (%s, %s, %s, %s, %s, %s)
2023-06-05 14:21:59,421 INFO sqlalchemy.engine.Engine [cached since 0.001368s ago] ('https://huggingface.co/datasets/acronym_identification/resolve/refs%2Fconvert%2Fparquet/default/acronym_identification-train.parquet', 1657991, 'acronym_identification. Config: default. Split: train', None, 'acronym_identification-train.parquet', 2)
2023-06-05 14:21:59,421 INFO sqlalchemy.engine.Engine INSERT INTO data_download (content_url, content_size_kb, description, encoding_format, name, dataset_identifier) VALUES (%s, %s, %s, %s, %s, %s)
2023-06-05 14:21:59,421 INFO sqlalchemy.engine.Engine [cached since 0.001828s ago] ('https://huggingface.co/datasets/acronym_identification/resolve/refs%2Fconvert%2Fparquet/default/acronym_identification-validation.parquet', 206916, 'acronym_identification. Config: default. Split: validation', None, 'acronym_identification-validation.parquet', 2)
2023-06-05 14:21:59,912 INFO sqlalchemy.engine.Engine SELECT publication.platform, publication.platform_identifier, publication.title, publication.doi, publication.creators, publication.access_right, publication.date_created, publication.date_published, publication.url, publication.identifier, publication.license_identifier, publication.resource_type_identifier 
FROM publication 
WHERE publication.platform = %s AND publication.platform_identifier = %s
2023-06-05 14:21:59,912 INFO sqlalchemy.engine.Engine [cached since 0.5146s ago] ('huggingface', 'GURULINGAPPA2012885')
2023-06-05 14:21:59,913 INFO sqlalchemy.engine.Engine INSERT INTO ai_asset (type) VALUES (%s)
2023-06-05 14:21:59,913 INFO sqlalchemy.engine.Engine [cached since 0.5139s ago] ('publication',)
2023-06-05 14:21:59,914 INFO sqlalchemy.engine.Engine INSERT INTO publication (platform, platform_identifier, title, doi, creators, access_right, date_created, date_published, url, identifier, license_identifier, resource_type_identifier) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
2023-06-05 14:21:59,914 INFO sqlalchemy.engine.Engine [cached since 0.5123s ago] ('huggingface', 'GURULINGAPPA2012885', 'Development of a benchmark corpus to support the automatic extraction of drug-related adverse effects from medical case reports', None, None, None, None, None, None, 3, None, None)
2023-06-05 14:21:59,915 INFO sqlalchemy.engine.Engine SELECT dataset.platform, dataset.platform_identifier, dataset.description, dataset.name, dataset.same_as, dataset.contact, dataset.creator, dataset.publisher, dataset.date_modified, dataset.date_published, dataset.funder, dataset.is_accessible_for_free, dataset.issn, dataset.size, dataset.spatial_coverage, dataset.temporal_coverage_from, dataset.temporal_coverage_to, dataset.version, dataset.identifier, dataset.license_identifier 
FROM dataset 
WHERE dataset.platform = %s AND dataset.platform_identifier = %s
2023-06-05 14:21:59,915 INFO sqlalchemy.engine.Engine [cached since 0.5114s ago] ('huggingface', 'ade_corpus_v2')
2023-06-05 14:21:59,916 INFO sqlalchemy.engine.Engine INSERT INTO ai_asset (type) VALUES (%s)
2023-06-05 14:21:59,916 INFO sqlalchemy.engine.Engine [cached since 0.5166s ago] ('dataset',)
2023-06-05 14:21:59,918 INFO sqlalchemy.engine.Engine INSERT INTO license (name) VALUES (%s)
2023-06-05 14:21:59,918 INFO sqlalchemy.engine.Engine [cached since 0.5106s ago] ('unknown',)
2023-06-05 14:21:59,918 INFO sqlalchemy.engine.Engine INSERT INTO keyword (name) VALUES (%s)
2023-06-05 14:21:59,919 INFO sqlalchemy.engine.Engine [cached since 0.5086s ago] ('task_categories:text-classification',)
2023-06-05 14:21:59,919 INFO sqlalchemy.engine.Engine INSERT INTO keyword (name) VALUES (%s)
2023-06-05 14:21:59,919 INFO sqlalchemy.engine.Engine [cached since 0.5092s ago] ('task_categories:token-classification',)
2023-06-05 14:21:59,920 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/home/apprunner/.local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "/home/apprunner/.local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/apprunner/.local/lib/python3.11/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry 'task_categories:token-classification' for key 'keyword.name'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/main.py", line 185, in <module>
    main()
  File "/app/main.py", line 181, in main
    uvicorn.run("main:create_app", host="0.0.0.0", reload=args.reload, factory=True)
  File "/home/apprunner/.local/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/apprunner/.local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/apprunner/.local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/apprunner/.local/lib/python3.11/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = self.loaded_app()
                      ^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 166, in create_app
    populate_database(
  File "/app/database/setup.py", line 90, in populate_database
    session.flush()
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
    self._flush(objects)
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3525, in _flush
    with util.safe_reraise():
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
    flush_context.execute()
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/apprunner/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/home/apprunner/.local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "/home/apprunner/.local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/apprunner/.local/lib/python3.11/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'task_categories:token-classification' for key 'keyword.name'")
[SQL: INSERT INTO keyword (name) VALUES (%s)]
[parameters: ('task_categories:token-classification',)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

## Steps to reproduce (all issues):
```sh
git checkout develop
docker build --tag ai4eu_server_demo:latest -f Dockerfile . 
docker run --network sql-network -it --rm -p 8001:8000 --name apiserver ai4eu_server_demo --rebuild-db always --populate-datasets huggingface --limit 5
```

## Further recommendations
* Would it be possible to define concrete versions of dependencies in pyproject.toml config file? This error was likely caused by the breaking change in one of the libraries.

**Comment by josvandervelde** [comment]
Thanks for this issue and these suggestions!
We just merged https://github.com/aiondemand/AIOD-rest-api/pull/66, it should be fixed now!

1. We changed the HuggingFace connector towards using `itertools.islice(`, as you suggested
2. We fixed the integrity errors for the connectors

The versions of the dependencies are not fixed yet. We'll do that in another PR. 

I'm closing this issue for now. Please reopen it if something is incorrect!
